#####################################################
##   SecureCRT Sessions Configuration File   ##
#####################################################
#
# This file contains the base configuration for ALAB2CRT.
# It defines the directory structure and provider settings.
#
# Required parameters:
#   - crt_path: The root directory for SecureCRT sessions
#   - directory: Directory structure for each provider
#
# Note:
#   - If crt_path is not specified, the default path will be used:
#     - Windows: C:\Documents and Settings\{USER_NAME}\Application Data\VanDyke\Config\Sessions
#     - Mac    : /Users/{USER_NAME}/Library/Application Support/VanDyke/SecureCRT/Config/Sessions
#   - The directory structure will be created automatically under the crt_path
#
# Directory structure:
#   crt_path
#     └ top_dir            : Top-level directory for each provider
#        ├ dirA            : Lab-specific directories
#        ⎪  └ jumphost_dir : Directory for jumphost sessions
#        ├ dirB
#        └ ...
#
crt_path: 

##########################################
##   Directory Configuration   ##
##########################################
#
# Defines the directory structure for each provider.
# Each provider has its own top-level directory and jumphost directory.
#
directory:
  # ATD (Arista Test Drive) provider settings
  atd:
    # Top-level directory for ATD sessions
    top_dir: ATD
    # Directory for ATD jumphost sessions
    jumphost_dir: jumphost

  # ACT (Arista Cloud Test) provider settings
  act:
    # Top-level directory for ACT sessions
    top_dir: ACT
    # Directory for ACT jumphost sessions
    jumphost_dir: jumphost 